#!/bin/bash

############
#---POST---#
############

curl -X POST -H 'Content-Type: application/json' -d '{"resource":"FUBAR"}' http://localhost:8080/test
echo -e '\n'

#curl -H 'Content-Type: application/json' -X PUT -d '{"tags":["tag1","tag2"],"question":"Which band?","answers":[{"id":"a0","answer":"Answer1"},{"id":"a1","answer":"answer2"}]}' 


# colnames for DB creation
curl -X POST -H 'Content-Type: application/json' -d '{"colnames":["name1","name2","name3"]}' http://localhost:8080/colnames


###########
#---GET---#
###########

curl -X GET http://localhost:8080/test
echo -e '\n'

exit 0
